### ISSUE TITLE
Tv shows support

### ISSUE THREAD

**Issue by ares** [ekarorgit/metadata.csfd.cz#1]
Iy seems this awesome addon can't be used as metadata source for tv shows in my Kodi 17 instance. Works well for movies though.

**Comment by ekarorgit** [comment]
Yes, it is only for movies. Not planning to expand it for tv series in near time, as there is metadata.serialozne.cz in my other repo which I am using...

**Comment by ares** [comment]
oh, good to know, I'll use that one, thanks!
