### ISSUE TITLE
fanart

### ISSUE THREAD

**Issue by xardas1977** [ekarorgit/metadata.csfd.cz#10]
Asi mesiac mi nestahuje fanarty z tmdb.org, dalo by sa  s tym nieco urobit? alebo je chyba len u mna? Dakujem - pouzivam posledne verzie csfd 3.10 aj tmdb.org

**Comment by ekarorgit** [comment]
zkousel jsem s verzi 3.10 a vse funguje jak ma. Prosim zkontroluj nastaveni pluginu jak globalni tak lokani ohledne stahovani fanartu z TMDB. Pokud bude problem pretrvavat tak posli nazev filmu pro ktery to nefunguje, screenshot nastaveni pluginu, a log kde se snazis oscrapovat film.
