### ISSUE TITLE
Nazev souboru misto nazvu filmu

### ISSUE THREAD

**Issue by kibkib** [ekarorgit/metadata.csfd.cz#12]
Užitečný plugin.
Nešlo by prosím přidat volbu , aby se u filmu zobrazil název souboru místo názvu filmu?
Tedy k volbě local, original, en, cs, sk přidat vobu filename.

Přijde mi to užitečné, protože u dost filmů se stáhne špatný popis a pak nevím, k čemu to vlastně patří.
Děkuji

**Comment by ekarorgit** [comment]
@kibkib neni problem dodelat nazev souboru, ale nebude to uplne presne. ve scraperu je k dispozici nazev souboru oklesten o ruzne tagy apod, co dela interne Kodi.
Jen mi nejak unika pouziti, protoze se presne podle toho oklesteneho nazvu souboru hleda na csfd, takze kdyby si tam dal clovek neco jineho, tak to dohleda spatnej film.

Jinak kod je hotovej v branchi https://github.com/ekarorgit/metadata.csfd.cz/tree/filename_title tak to muzes ozkouset...

**Comment by kibkib** [comment]
Šlo by prosím obnovit branch s volbou filename (nebo nejlépe tuto funkci zahrnout do master)? Fungovalo to dobře (omluvám se, že jsem to nenapsal, chtěl jsem to déle testovat a pak už na to zapomněl). 
Chci to z důvodu, že když se k filmu z CSFD přiřadí chybný film, dojde i k přejmenování názvu na chybný. S funkcí filename mi zůstane alespoň původní název souboru se správným názvem filmu (a jen popis a fanart bude chybný).
Děkuji
