### ISSUE TITLE
Addon nefunguje - 'Unable to connect to remote server'

### ISSUE THREAD

**Issue by POWL-CZ** [ekarorgit/metadata.csfd.cz#15]
Pri snaze pridat film do knihovny:
Chyba 'Unable to connect to remote server'
LOG: 
CCurFile::Open failed with code 403...
CCurlFile::FillBuffer - Failed: HTTP returned error 403

**Comment by goliashcz** [comment]
Řekl bych, že CSFD server začal blokovat KODI user agent. Když jsem změnil User Agent (podle tohohle https://forum.kodi.tv/showthread.php?tid=61789), tak mi requesty procházely.

**Comment by Pekolik** [comment]
Zřejmě se oprava nepovedla úplně - při přidávání filmu do knihovny se zasekne a nic se neděje - pouze stoupá využitá paměť. Není tam někde nekonečná smyčka či rekurze?

**Comment by goliashcz** [comment]
Podle mě se neměl použít https protokol pro akas.imdb.com requesty.
