### ISSUE TITLE
Freeze Kodi

### ISSUE THREAD

**Issue by Deffa007** [ekarorgit/metadata.csfd.cz#17]
Hello. I updated the metadata Kodi csfd and then I'm in trouble.
Approximately 25% of the scan hangs, slow down across the board starts and Kodi Kodi stopped working.

After uninstalling csfd metadata version 3.13 Kodi goes without problems

We tried to Kodi 17.6 Kryprton on version 18.5 Leia

Please help with the solution

Zdravím. 
Aktualizoval jsem v Kodi metadata csfd a následně mám problémy.
Zhruba v 25% se prohledávání zasekne, zpomalý celé Kodi a naskočí tabule Kodi přestal pracovat.

Po odinstalování csfd metadata verze 3.13 Kodi jede bez problémů

Vyzkoušel jsme na Kodi 17.6 Kryprton i na verzi 18.5 Leia

Prosím o pomoc s řešením

**Comment by ghost** [comment]
I suffer from the same issue. Running 18.5 Leia on Philips Android TV. Scan hangs always at the same movie - Folder name: "Alenka v risi divu - Za zrcadlem (2016)" and Kodi becomes almost unresponsive.

**Comment by Pekolik** [comment]
Jak jsem psal v #15 - skenování se zastaví a jen stoupá využití paměti až KODI "umře". V logu jsem tu nekonečnou smyčku našel - přikládám.
Od načtení detailu z ČSFD dojde k dotazu na AKAS.IMDB.COM, který skončí s chybou 404. Tento dotaz je opakován stále dokola až do vyčerpání veškeré dostupné paměti.

[kodi_csfd.log](https://github.com/ekarorgit/metadata.csfd.cz/files/3900220/kodi_csfd.log)

**Comment by Deffa007** [comment]
Jak se píše v #15 tak použití https není funkční. Je požadován bezpečnostní protokol a znovu a znovu se opakuje dotaz. Když jsem do prohlížeče zadal http, tak je to průchozí. Nedá se to změnit v programu?
Zkoušel jsem v nastavení CSFD vypustit dotaz na IMBD a nic. Ale to je jen amaterský pokus..

U mě se to sekne na filmuj The Killers - Boots a postupně se zatěžuje a zatěžuje pamět až do zaseknutí celého stroje.

**Comment by Pekolik** [comment]
Ale v tom logu, co jsem připojil, není problém ve volání https na server csfd - problém nastane při volání http na server imdb, kdy se do URL nedostane název filmu, tudíž URL je "http://akas.imdb.com/title//" a toto volání skončí chybou 404. A zde nastává rekurze.

**Comment by Pekolik** [comment]
Tak už jsem na to asi přišel, ale bohužel nevím, jak to spravit... V detailu filmu z ČSFD nepřišel odkaz na IMDB, tudíž se nenašlo ID filmu a tím se nedostal text do odkazu na stažení detailu z IMDB. Nevím, jestli je ta chyba 404 nějakým novým chováním IMDB, každopádně teď se na tom vyhledání informací o filmu cyklí :(

**Comment by pvagner** [comment]
Mám ten istý problém, väčšinou sa to deje pre české a slovenské filmy, ktoré nie sú na IMDB, Respo. ako píše @Pekolik Neviem prísť na to, ako to ošetriť.

**Comment by ekarorgit** [comment]
There were more changes needed to fix those issues properly - see v3.15

- whole akas.imdb.com stopped working - switched to common functions from metadata.common.imdb
- changes how the buffers are cleared in kodi caused the infinite loop issue
