### ISSUE TITLE
Missing poster

### ISSUE THREAD

**Issue by tvavrys** [ekarorgit/metadata.csfd.cz#5]
I'm unable to get a poster for "Wolf of Wall Street". I enabled all data fallbacks and still no luck.

**Comment by ekarorgit** [comment]
Can you try with the latest version 3.10?
I have tried with film and directory named "wolf of wall street" with default settings with v3.10 and got all posters:
```
DEBUG: scraper: GetIMDBThumb returned <details><thumb>https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@.jpg</thumb></details>

DEBUG: scraper: ParseTMDBThumbs returned <details><thumb aspect="poster" preview="http://image.tmdb.org/t/p/w500/xc06sPDDc4SgDo8Pmy1qLgvMY3P.jpg">http://image.tmdb.org/t/p/original/xc06sPDDc4SgDo8Pmy1qLgvMY3P.jpg</thumb>
...
<thumb aspect="poster" preview="http://image.tmdb.org/t/p/w500/dx8ikU8UC4OlZv4u2Y5vcrVqUTN.jpg">http://image.tmdb.org/t/p/original/dx8ikU8UC4OlZv4u2Y5vcrVqUTN.jpg</thumb></details>

DEBUG: scraper: GetCSFDDetails returned <details><title>Vlk z Wall Street (The Wolf of Wall Street)</title>
...
<thumb>http://img.csfd.cz/files/images/film/posters/158/174/158174978_79cad9.jpg</thumb></details>
```

**Comment by tvavrys** [comment]
@ekarorgit I updated to the latest version (master branch) and still no luck.

This is the folder name: `The Wolf of Wall Street (2013)`
This is the movie file name: `The Wolf of Wall Street (2013) Bluray-1080p.mkv`

**Comment by ekarorgit** [comment]
@tvavrys please can you send me kodi.log from seesion where you try to load the metadata for the film again? Usual directory on Windows is AppData/Roaming/Kodi
example: c:\Users\Tomas\AppData\Roaming\Kodi\kodi.log
Be sure that there is no *.nfo file in the directory as kodi can take it as metadata - https://kodi.wiki/view/NFO_files
Also good help from users on xbmc forum - http://www.xbmc-kodi.cz/prispevek-scraper-%C4%8Dsfd-cz

**Comment by tvavrys** [comment]
@ekarorgit 

The poster is available but Kodi can't load it in LibreELEC (RPI3). Could it be due to `http` to `https` redirect?

```
10:15:59.955 T:1457517472 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:16:00.784 T:1457517472 WARNING: Previous line repeats 1 times.
10:16:00.784 T:1457517472  NOTICE: LoadJpeg: unable to load http://img.csfd.cz/files/images/film/posters/158/174/158174978_79cad9.jpg
10:16:02.290 T:1457517472   ERROR: ExtractFrame: Could not decode a frame
```

**Comment by ekarorgit** [comment]
From logs, it looks to me that librelec RPI3 cannot load this specific JPEG (googled it and seems to me as common issue). What is interesting is the ERROR afterwards on ExtractFrame ?
Doesn't seems to be connected to this scraper, as it only get the xml metadata about the movie with url to pictures. Try to ask on kodi forums: ie http://www.xbmc-kodi.cz/
Thanks
