### ISSUE TITLE
Missing actors when storing on MySQL

### ISSUE THREAD

**Issue by PetrM1** [ekarorgit/metadata.csfd.cz#6]
Hi all,

I do have setup movie DB share via MySQL. When I grab information on PC it works well and actors are available even with thumbnails. When I later on open it from synced from MySQL on KODI on raspberry all goes well except actors.
I've seen similar issue (missing actor info on MySQL) on IMDB scrapper, but I haven't figured out what was the root. Has anybody tried the same setup and have same issue?

Thanks
Petr

**Comment by ekarorgit** [comment]
I haven't tried It doesn't seem to be connected to this particular scraper, so I will close the issue. 
Try asking on kodi forums - for example:  http://www.xbmc-kodi.cz/
