### ISSUE TITLE
Support for TV Shows (seriály)

### ISSUE THREAD

**Issue by panther7** [ekarorgit/metadata.csfd.cz#7]
Hi,

please add support for tv shows.

Thanks

**Comment by ekarorgit** [comment]
CSFD doesn't have needed data for tv shows - it doesn't have even the name of the episodes....
There are other plugins for series serailzone.cz, TVDB....

**Comment by panther7** [comment]
@ekarorgit Ahoj, dneska jsem kontroloval na ČSFD seriály a u většiny, teda aspoň co já sleduji, tak obsahují názvy epizod. Navíc ČSFD má lepší databázi než serialzone, TVDb či TMDb. 

Bylo by fajn, naučit ten doplněk i seriály :-)
