### ISSUE TITLE
Pridanie slovenčiny

### ISSUE THREAD

**Issue by mvalec** [ekarorgit/metadata.csfd.cz#8]
Ahoj, pridaj prosím podporu slovenčiny.
Vopred ďakujem.
[metadata.csfd.cz-SK.zip](https://github.com/ekarorgit/metadata.csfd.cz/files/1990838/metadata.csfd.cz-SK.zip)

**Comment by panther7** [comment]
Hezký ;-)

**Comment by ekarorgit** [comment]
Co myslis podporou slovenciny? Jako konfigurace a popis pluginu?
Bohuzel nejsem slovak a opravdu si netroufnu prekladat do slovenciny.
Ale rad ji pridam, kdyz se toho chytnes, prelozis dva soubory:
https://github.com/ekarorgit/metadata.csfd.cz/blob/master/addon.xml
https://github.com/ekarorgit/metadata.csfd.cz/blob/master/resources/language/Czech/strings.xml
a nejlepe jeste udelas pull request...

**Comment by mvalec** [comment]
Preklad som už dávno urobil, je v tom prvom príspevku. Len som si nie istý zmenami v  súbore /resource/settings.xml.

**Comment by ekarorgit** [comment]
Nejak jsem si nevsiml zes uz to pridal predtim :) Jinak bych to tam nahodil sam...
Dik za pull request, uz je mergnuty a verze zvednuta na 3.11
